dbAddress: hollowbit.net:3306
dbUsername: testserverlogin
dbPassword: HvQQwsk9Ed2A9Ysx
name: Emerald
hbServerAddress: loginserver.hollowbit.net:22123
hbServerPassword: astrongpassword
motd: Welcome to Archipelo!
region: 0
spawnIsland: Archipelo
spawnMap: island
spawnX: 360.0
spawnY: 400.0