dbAddress: localhost:3306
dbUsername: root
dbPassword: password
name: Emerald
hbServerAddress: localhost:22123
hbServerPassword: astrongpassword
motd: Welcome to Archipelo!
region: 0
spawnIsland: Archipelo
spawnMap: Island
spawnX: 360.0
spawnY: 400.0