dbAddress: localhost:3306
dbUsername: root
dbPassword: password
name: Emerald
hbServerAddress: localhost:22123
hbServerPassword: astrongpassword
motd: Welcome to Archipelo!
region: 0
spawnIsland: TestIsland
spawnMap: island
spawnX: 720.0
spawnY: 208.0