dbAddress: hollowbit.net:3306
dbUsername: testserverlogin
dbPassword: HvQQwsk9Ed2A9Ysx
name: Emerald
hbServerAddress: 144.217.163.60:22123
hbServerPassword: astrongpassword
motd: Welcome to Archipelo!
region: 0
spawnMap: world
spawnX: -160.0
spawnY: 624.0