dbAddress: hollowbit.net:3306
dbUsername: testserverlogin
dbPassword: HvQQwsk9Ed2A9Ysx
name: Emerald
hbServerAddress: hollowbit.net:22123
hbServerPassword: astrongpassword
motd: Welcome to Archipelo!
region: 0
spawnIsland: TestIsland
spawnMap: island
spawnX: 720.0
spawnY: 208.0