dbAddress: localhost:3306
dbUsername: root
dbPassword: password
name: Emerald
hbServerAddress: localhost:22123
hbServerPassword: astrongpassword
motd: Welcome to Archipelo!
region: 0
spawnIsland: archipelo
spawnMap: island
spawnX: 0.0
spawnY: 0.0